env: dev

app_name: local-pipeline

kafka:
  bootstrap_servers: localhost:9092
  topic: events

paths:
  silver: s3a://silver/events/
  gold: s3a://gold/aggregated/

streaming:
  watermark: "1 minute"
  window: "1 minute"

spark:
  app_name: "adtech-pipeline"
  checkpoint: "/tmp/checkpoint"

minio:
  endpoint: "http://localhost:9000"
  access_key: "minio"
  secret_key: "minio123"
