name: CI Pipeline

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

jobs:
  ci:
    name: CI (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      # -------------------------
      # CHECKOUT
      # -------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # PYTHON SETUP
      # -------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # -------------------------
      # CACHE
      # -------------------------
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}

      # -------------------------
      # INSTALL
      # -------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[streaming,batch,dashboard,dev]

      # -------------------------
      # LINT
      # -------------------------
      - name: Run Black
        run: black --check .

      - name: Run isort
        run: isort --check-only .

      - name: Run Ruff
        run: ruff check .

      # -------------------------
      # TESTS
      # -------------------------
      - name: Run tests
        run: pytest

      # -------------------------
      # BUILD PACKAGE 📦
      # -------------------------
      - name: Build package
        run: |
          pip install build
          python -m build

      # -------------------------
      # UPLOAD ARTIFACT 📤
      # -------------------------
      - name: Upload Python artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/

  docker-build:
    name: Docker Build Check
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # BUILD IMAGE 🐳
      # -------------------------
      - name: Build Docker Image
        run: docker build -t ml-pipeline:test .

      # -------------------------
      # SAVE IMAGE (OPCIONAL)
      # -------------------------
      - name: Save Docker image
        run: docker save ml-pipeline:test | gzip > pipeline.tar.gz

      # -------------------------
      # UPLOAD DOCKER ARTIFACT
      # -------------------------
      - name: Upload Docker artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: pipeline.tar.gz
